### ISSUE TITLE
SettingsService with baseVariants

### ISSUE THREAD

**Issue by Bruno86** [cdaecke/md_saml#62]
Hello,
SettingsService dont use baseVariants.
For exemple i got this settings : 
```
md_saml:
  mdsamlSpBaseUrl: "https://mysite.com"
  fe_users:
    createIfNotExist: true
    updateIfExist: true
  saml:
    sp:
      entityId: "/typo3/index.php?loginProvider=1648123062&mdsamlmetadata&loginType=frontend"
      assertionConsumerService:
        url: "/typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs&logintype=login"
    idp:
      entityId: "https://myauth.com/saml/sp/metadata/default-sp"
      singleSignOnService:
        url: "https://myauth.com/saml/idp/singleSignOnService"
   
baseVariants:
  - condition: 'applicationContext == "Development"'
    md_saml:
      mdsamlSpBaseUrl: "https://local.mysite.com:7443"
      saml:
        idp:
          entityId: "https://local.myauth.com/saml/sp/metadata/default-sp"
          singleSignOnService:
            url: "https://local.myauth.com/saml/idp/singleSignOnService"
  - condition: 'applicationContext == "Development/Testing"'
    md_saml:
      mdsamlSpBaseUrl: "https://validation.mysite.com:7443"
      saml:
        idp:
          entityId: "https://validation.myauth.com/saml/sp/metadata/default-sp"
          singleSignOnService:
            url: "https://validation.myauth.com/saml/idp/singleSignOnService"
```

To make it work I had to change this code in SettingsService.php : 

```
    /**
     * Get SAML configuration
     *
     * @return array
     */
    private function getSamlConfig(): array
    {
        $siteUrl = GeneralUtility::getIndpEnv('TYPO3_HOST_ONLY');

        /** @var Site $site */
        foreach (GeneralUtility::makeInstance(SiteFinder::class)->getAllSites() as $site) {
            if ($site->getBase()->getHost() === $siteUrl) {
                $settings = $site->getConfiguration()['settings']['md_saml']?? [];
                return $this->getConfigurationWithBaseVariants(
                    $settings,
                    $site->getConfiguration()['settings']['baseVariants']?? []
                );
            }

            foreach ($site->getLanguages() as $language) {
                if ($language->getBase()->getHost() == $siteUrl) {
                    $settings = $site->getConfiguration()['settings']['md_saml']?? [];
                    return $this->getConfigurationWithBaseVariants(
                        $settings,
                        $site->getConfiguration()['settings']['baseVariants']?? []
                    );
                }
            }
        }

        throw new \RuntimeException('The site configuration could not be resolved.', 1648646492);
    }
    
    /**
     * Get SAML configuration with baseVariants
     *
     * @param array $mdSamlSettings
     * @param array|null $baseVariants
     * @return array
     */
    private function getConfigurationWithBaseVariants(array $mdSamlSettings, ?array $baseVariants): array
    {
        $overrideSettings = [];
        if (!empty($baseVariants)) {
            $expressionLanguageResolver = GeneralUtility::makeInstance(
                Resolver::class,
                'site',
                []
            );
            foreach ($baseVariants as $baseVariant) {
                try {
                    if ((bool)$expressionLanguageResolver->evaluate($baseVariant['condition'])) {
                        $overrideSettings = $baseVariant['md_saml'];
                        break;
                    }
                } catch (SyntaxError $e) {
                    // silently fail and do not evaluate
                    // no logger here, as Site is currently cached and serialized
                }
            }
        }

        return array_replace_recursive($mdSamlSettings, $overrideSettings);
    }
```
